"""초기 FX 스키마

Revision ID: d408d00df25f
Revises: 
Create Date: 2026-08-30 11:28:48.969857

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd408d00df25f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('quote_unit', sa.SmallInteger(), nullable=False),
    sa.Column('source_item_code', sa.String(length=20), nullable=False),
    sa.Column('first_available_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('fx_collection_job',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('range_start', sa.Date(), nullable=False),
    sa.Column('range_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('chunks_total', sa.Integer(), nullable=False),
    sa.Column('chunks_done', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_currency_status', 'fx_collection_job', ['currency_code', 'status'], unique=False)
    op.create_table('fx_coverage',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('covered_from', sa.Date(), nullable=False),
    sa.Column('covered_through', sa.Date(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('currency_code')
    )
    op.create_table('fx_rate',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quote_unit', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('currency_code', 'quote_date')
    )
    op.create_table('fx_spread',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('cash_buy', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('cash_sell', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('remit_send', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('remit_receive', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('currency_code')
    )
    op.create_table('fx_collection_lock',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['job_id'], ['fx_collection_job.id'], ),
    sa.PrimaryKeyConstraint('currency_code')
    )
    op.create_table('fx_raw_response',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('requested_from', sa.Date(), nullable=False),
    sa.Column('requested_to', sa.Date(), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=False),
    sa.Column('result_code', sa.String(length=20), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['job_id'], ['fx_collection_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_currency_range', 'fx_raw_response', ['currency_code', 'requested_from', 'requested_to'], unique=False)
    op.create_index('ix_raw_received_at', 'fx_raw_response', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_received_at', table_name='fx_raw_response')
    op.drop_index('ix_raw_currency_range', table_name='fx_raw_response')
    op.drop_table('fx_raw_response')
    op.drop_table('fx_collection_lock')
    op.drop_table('fx_spread')
    op.drop_table('fx_rate')
    op.drop_table('fx_coverage')
    op.drop_index('ix_job_currency_status', table_name='fx_collection_job')
    op.drop_table('fx_collection_job')
    op.drop_table('currency')
    # ### end Alembic commands ###
